/* THIS FILE HAS BEEN AUTOMATICALLY GENERATED BY LLnextgen. DO NOT EDIT */
#ifndef  __LLNEXTGEN_LL_H__
#define __LLNEXTGEN_LL_H__
#ifndef LL_NOTOKENS
#define EOFILE 256
#define LPAR 257
#define PLUS 258
#define RPAR 259
#define ATOK 260
#define BTOK 261
#endif
#define LL_MAXTOKNO 261
#define LL_MISSINGEOF (-1)
#define LL_DELETE (0)
#define LL_VERSION 0x000505L
#define LL_NEW_TOKEN (-2)
void parser(void);
extern int LLsymb;
#endif
