/* THIS FILE HAS BEEN AUTOMATICALLY GENERATED BY LLnextgen. DO NOT EDIT */
#ifndef  __LLNEXTGEN_LL_H__
#define __LLNEXTGEN_LL_H__
#ifndef LL_NOTOKENS
#define EOFILE 256
#define EOF_TOK 257
#define BEGIN_TOK 258
#define END_TOK 259
#define COMMENT 260
#define PROGRAM_TOK 261
#define DOBEGIN_TOK 262
#define DOEND_TOK 263
#define IFBEGIN_TOK 264
#define IFEND_TOK 265
#define FUNCTION_TOK 266
#define OR_OP 267
#define AND_OP 268
#define CAND_OP 269
#define COR_OP 270
#define ASSIGNMENT_OP 271
#define PLUS_OP 272
#define MUL_OP 273
#define POW_OP 274
#define COMPARE_OP 275
#define TYPE_OP 276
#define VAR_TOK 277
#define VARIABLE 278
#define NUMBER 279
#define STRING 280
#define BOOLEAN 281
#define THEN_TOK 282
#define CONSTANT_TOK 283
#define COMMA 284
#define SEMICOLON 285
#define ALTGUARD 286
#define FUNCNAME 287
#define PROGRAMNAME 288
#define IDENTIFIER 289
#define NOT_TOK 290
#define TYPE 291
#define EOL 292
#define ERROR 293
#define DOT 294
#define LPARREN 295
#define RPARREN 296
#define PROCEDURE_TOK 297
#define WHITESPACE 298
#endif
#define LL_MAXTOKNO 298
#define LL_MISSINGEOF (-1)
#define LL_DELETE (0)
#define LL_VERSION 0x000505L
#define LL_NEW_TOKEN (-2)
void parser(void);
extern int LLsymb;
#endif
