/* THIS FILE HAS BEEN AUTOMATICALLY GENERATED BY LLnextgen. DO NOT EDIT */
#ifndef  __LLNEXTGEN_LL_H__
#define __LLNEXTGEN_LL_H__
#ifndef LL_NOTOKENS
#define EOFILE 256
#define BEGIN_TOK 257
#define END_TOK 258
#define COMMENT 259
#define PROGRAM_TOK 260
#define DOBEGIN_TOK 261
#define DOEND_TOK 262
#define IFBEGIN_TOK 263
#define IFEND_TOK 264
#define FUNCTION_TOK 265
#define PRINT_TOK 266
#define READ_TOK 267
#define OR_OP 268
#define AND_OP 269
#define CAND_OP 270
#define COR_OP 271
#define ASSIGNMENT_OP 272
#define PLUS_OP 273
#define MIN_OP 274
#define MUL_OP 275
#define POW_OP 276
#define COMPARE_OP 277
#define TYPE_OP 278
#define VAR_TOK 279
#define VARIABLE 280
#define NUMBER 281
#define STRING 282
#define BOOLEAN 283
#define THEN_TOK 284
#define CONSTANT_TOK 285
#define COMMA 286
#define SEMICOLON 287
#define ALTGUARD 288
#define FUNCNAME 289
#define PROGRAMNAME 290
#define IDENTIFIER 291
#define NOT_TOK 292
#define TYPE 293
#define EOL 294
#define ERROR 295
#define DOT 296
#define LPARREN 297
#define RPARREN 298
#define PROCEDURE_TOK 299
#define WHITESPACE 300
#endif
#define LL_MAXTOKNO 300
#define LL_MISSINGEOF (-1)
#define LL_DELETE (0)
#define LL_VERSION 0x000505L
#define LL_NEW_TOKEN (-2)
void parser(void);
const char *LLgetSymbol(int);
extern int LLsymb;
#endif
