/* THIS FILE HAS BEEN AUTOMATICALLY GENERATED BY LLnextgen. DO NOT EDIT */
#ifndef  __LLNEXTGEN_LL_H__
#define __LLNEXTGEN_LL_H__
#ifndef LL_NOTOKENS
#define EOFILE 256
#define BEGIN_TOK 257
#define END_TOK 258
#define COMMENT 259
#define PROGRAM_TOK 260
#define DOBEGIN_TOK 261
#define DOEND_TOK 262
#define IFBEGIN_TOK 263
#define IFEND_TOK 264
#define FUNCTION_TOK 265
#define OR_OP 266
#define AND_OP 267
#define CAND_OP 268
#define COR_OP 269
#define ASSIGNMENT_OP 270
#define PLUS_OP 271
#define MUL_OP 272
#define POW_OP 273
#define COMPARE_OP 274
#define TYPE_OP 275
#define VAR_TOK 276
#define VARIABLE 277
#define NUMBER 278
#define STRING 279
#define BOOLEAN 280
#define THEN_TOK 281
#define CONSTANT_TOK 282
#define COMMA 283
#define SEMICOLON 284
#define ALTGUARD 285
#define FUNCNAME 286
#define PROGRAMNAME 287
#define IDENTIFIER 288
#define NOT_TOK 289
#define TYPE 290
#define EOL 291
#define ERROR 292
#define DOT 293
#define LPARREN 294
#define RPARREN 295
#define PROCEDURE_TOK 296
#define WHITESPACE 297
#endif
#define LL_MAXTOKNO 297
#define LL_MISSINGEOF (-1)
#define LL_DELETE (0)
#define LL_VERSION 0x000505L
#define LL_NEW_TOKEN (-2)
void parser(void);
const char *LLgetSymbol(int);
extern int LLsymb;
#endif
